sservices:
  - type: web
    name: academyofmagic-bot
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --worker-class gevent --timeout 60 --max-requests 100 --max-requests-jitter 20
    plan: free
